{"uuid": "6be02d68-e831-4bc9-8123-04969864bc78", "children": ["fe5e69ab-1cd8-4d13-b835-3d4e1751be33"], "befores": [{"name": "driver", "status": "passed", "start": 1727702450555, "stop": 1727702455977}], "afters": [{"name": "driver::0", "status": "broken", "statusDetails": {"message": "KeyboardInterrupt\n", "trace": "  File \"C:\\Users\\vsavc\\PycharmProjects\\Diplom\\Diplom_3\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\vsavc\\PycharmProjects\\Diplom\\Diplom_3\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 907, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\vsavc\\PycharmProjects\\Diplom\\Diplom_3\\conftest.py\", line 26, in driver\n    driver.quit()\n  File \"C:\\Users\\vsavc\\PycharmProjects\\Diplom\\Diplom_3\\venv\\Lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 193, in quit\n    self.service.stop()\n  File \"C:\\Users\\vsavc\\PycharmProjects\\Diplom\\Diplom_3\\venv\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 149, in stop\n    self.send_remote_shutdown_command()\n  File \"C:\\Users\\vsavc\\PycharmProjects\\Diplom\\Diplom_3\\venv\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 134, in send_remote_shutdown_command\n    if not self.is_connectable():\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\vsavc\\PycharmProjects\\Diplom\\Diplom_3\\venv\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 123, in is_connectable\n    return utils.is_connectable(self.port)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\vsavc\\PycharmProjects\\Diplom\\Diplom_3\\venv\\Lib\\site-packages\\selenium\\webdriver\\common\\utils.py\", line 101, in is_connectable\n    socket_ = socket.create_connection((host, port), 1)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\vsavc\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\socket.py\", line 845, in create_connection\n    exceptions.clear()  # raise only the last error\n    ^^^^^^^^^^^^^^^^^^\n"}, "start": 1727702457551, "stop": 1727702464086}], "start": 1727702450555, "stop": 1727702464086}